name: CI
  
on:
  push:
    branches:
      - master
      - upcoming
  pull_request:
 
env:
  GAME_REVISION: 0
  GAME_LANGUAGE: ENGLISH
  COMPARE: 0
  UNUSED_ERROR: 1
  DEPRECATED_ERROR: 1

jobs:
  build-emerald:
    if: github.actor != 'allcontributors[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install binutils
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends binutils-arm-none-eabi gcc-arm-none-eabi libnewlib-arm-none-eabi libpng-dev python3

      - name: Cache build tools
        uses: actions/cache@v4
        with:
          path: |
            tools/bin2c/bin2c
            tools/gbafix/gbafix
            tools/gbagfx/gbagfx
            tools/jsonproc/jsonproc
            tools/mapjson/mapjson
            tools/mid2agb/mid2agb
            tools/preproc/preproc
            tools/ramscrgen/ramscrgen
            tools/rsfont/rsfont
            tools/scaninc/scaninc
            tools/trainerproc/trainerproc
            tools/compresSmol/compresSmol
            tools/compresSmol/compresSmolTilemap
            tools/wav2agb/wav2agb
          key: tools-${{ runner.os }}-${{ hashFiles('tools/*/Makefile', 'tools/**/*.c', 'tools/**/*.cpp', 'tools/**/*.h') }}

      - name: ROM (Emerald)
        env:
          GAME_VERSION: EMERALD
        run: make -j$(nproc) -O all

      - name: Upload ROM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pokeemerald-build
          path: |
            *.gba
